//
//  transDictionary.swift
//  Project Loca
//
//  Created by Tyler Angert on 3/28/17.
//  Copyright © 2017 TeamMilton370. All rights reserved.
//

import Foundation


var transDictionary: [String:String] = [
    "Vulpes macrotis" : "vulpes macrotis",
    "Capra ibex" : "Capra ibex",
    "Pongo pygmaeus" : "Pongo pygmaeus",
    "Sus scrofa" : "Sus scrofa",
    "Melursus ursinus" : "ursinus Melursus",
    "Ursus ursinus" : "ursinus Ursus",
    "German shepherd dog" : "perro pastor alem·n",
    "German police dog" : "perro de la policÌa alemana",
    "alsatian" : "alsaciano",
    "koala bear" : "oso koala",
    "kangaroo bear" : "oso canguro",
    "native bear" : "oso nativo",
    "Phascolarctos cinereus" : "Y cinereus",
    "spiny anteater" : "oso hormiguero espinoso",
    "anteater" : "oso hormiguero",
    "brush kangaroo" : "cepillo de canguro",
    "duckbill" : "ornitorrinco",
    "duckbilled platypus" : "ornitorrinco",
    "duck-billed platypus" : "ornitorrinco",
    "Ornithorhynchus anatinus" : "Ornithorhynchus anatinus",
    "six-gun" : "revÛlver",
    "six-shooter" : "revÛlver de seis tiros",
    "piano accordion" : "acordeÛn a piano",
    "squeeze box" : "caja de apretÛn",
    "emmet" : "hormiga",
    "pismire" : "pismire",
    "sea star" : "estrella de mar",
    "pearly nautilus" : "nautilo",
    "nautilus" : "nautilo",
    "grand" : "alto",
    "laptop computer" : "ordenador port·til",
    "military plane" : "aviÛn militar",
    "dirigible" : "dirigible",
    "containership" : "barco mercante",
    "container vessel" : "buque portacontenedores",
    "ocean liner" : "transatl·ntico",
    "pirate ship" : "barco pirata",
    "carrier" : "portador",
    "flattop" : "superficie plana",
    "attack aircraft carrier" : "portaaviones de ataque",
    "pigboat" : "pigboat",
    "sub" : "sub",
    "U-boat" : "Submarino alem·n",
    "army tank" : "tanque de guerra",
    "armored combat vehicle" : "vehÌculo de combate blindado",
    "armoured combat vehicle" : "vehÌculo de combate blindado",
    "bobsleigh" : "bobsleigh",
    "bob" : "chelÌn",
    "dog sled" : "trineo de perros",
    "dog sleigh" : "trineo de perros",
    "tandem bicycle" : "bicicleta t·ndem",
    "tandem" : "t·ndem",
    "all-terrain bike" : "bicicleta todo terreno",
    "off-roader" : "todoterreno",
    "coach" : "entrenador",
    "carriage" : "carro",
    "garden cart" : "carro de jardÌn",
    "lawn cart" : "la compra de cÈsped",
    "wheelbarrow" : "carretilla",
    "scooter" : "scooter",
    "amphibious vehicle" : "vehÌculo anfibio",
    "station wagon" : "carro de la estaciÛn",
    "wagon" : "vagÛn",
    "estate car" : "coche familiar",
    "beach waggon" : "vagÛn de playa",
    "station waggon" : "estaciÛn de vagÛn",
    "waggon" : "vagÛn",
    "hack" : "corte",
    "taxi" : "taxi",
    "taxicab" : "taxi",
    "landrover" : "landrover",
    "limo" : "limusina",
    "race car" : "coche de carreras",
    "racing car" : "coche de carreras",
    "sport car" : "carro deportivo",
    "golf cart" : "carro de golf",
    "snowplough" : "quitanieves",
    "fire truck" : "camiÛn de bomberos",
    "dustcart" : "camiÛn de basura,",
    "pickup truck" : "camioneta",
    "tow car" : "coche de remolque",
    "wrecker" : "destructor",
    "tractor trailer" : "Trailer tractor",
    "trucking rig" : "plataforma de transporte por carretera",
    "rig" : "aparejo",
    "articulated lorry" : "camiÛn articulado",
    "semi" : "semi",
    "police wagon" : "camioneta de la policÌa",
    "paddy wagon" : "coche celular",
    "patrol wagon" : "coche celular",
    "black Maria" : "coche celular",
    "RV" : "RV",
    "R.V." : "RV",
    "tram" : "tranvÌa",
    "tramcar" : "tranvÌa",
    "trolley" : "carretilla",
    "trolley car" : "tranvÌa",
    "manufactured home" : "casa prefabricada",
    "trike" : "triciclo",
    "velocipede" : "velocÌpedo",
    "monocycle" : "monociclo",
    "horse-cart" : "carro de caballos",
    "ricksha" : "rickshaw",
    "rickshaw" : "bicitaxi",
    "cot" : "cuna",
    "china closet" : "Armario de china",
    "medicine cabinet" : "botiquÌn",
    "commode" : "cÛmodo",
    "file cabinet" : "archivador",
    "filing cabinet" : "gabinete de presentaciÛn",
    "rocker" : "balancÌn",
    "day bed" : "cama de dÌa",
    "billiard table" : "mesa de billar",
    "snooker table" : "mesa de billar",
    "board" : "tablero",
    "closet" : "armario",
    "press" : "prensa",
    "ananas" : "piÒa",
    "jak" : "cÛmo",
    "jack" : "Jack",
    "rose hip" : "escaramujo",
    "rosehip" : "rosa mosqueta",
    "spike" : "espiga",
    "capitulum" : "capÌtulo",
    "horse chestnut" : "castaÒo de Indias",
    "conker" : "conker",
    "pipe organ" : "Ûrgano",
    "upright piano" : "piano vertical",
    "bell" : "campana",
    "gong" : "gong",
    "membranophone" : "membranophone",
    "tympan" : "tÌmpano",
    "tam-tam" : "tom-tom",
    "xylophone" : "xilÛfono",
    "violoncello" : "violoncelo",
    "fiddle" : "violÌn",
    "trumpet" : "trompeta",
    "trump" : "triunfo",
    "horn" : "cuerno",
    "mouth organ" : "Ûrgano bucal",
    "harp" : "arpa",
    "mouth harp" : "arpa de boca",
    "sweet potato" : "batata",
    "pandean pipe" : "tuberÌa pandean",
    "syrinx" : "siringe",
    "hautboy" : "oboe",
    "hautbois" : "oboe",
    "saxophone" : "saxofÛn",
    "transverse flute" : "flauta travesera",
    "yellow lady-slipper" : "amarilla seÒora-deslizador",
    "Cypripedium calceolus" : "calceolus cypripedium",
    "Cypripedium parviflorum" : "Cypripedium parviflorum",
    "drop" : "soltar",
    "drop-off" : "drop-off",
    "vale" : "valle",
    "headland" : "promontorio",
    "head" : "cabeza",
    "foreland" : "promontorio",
    "sand bar" : "barra de arena",
    "lakeshore" : "Lakeshore",
    "coast" : "costa",
    "seacoast" : "litoral",
    "sea-coast" : "litoral",
    "meat cleaver" : "cuchillo de carnicero",
    "chopper" : "helicÛptero",
    "paper knife" : "cuchillo de papel",
    "paperknife" : "paperknife",
    "carpenter's plane" : "El aviÛn de carpintero",
    "woodworking plane" : "plano de trabajo de la madera",
    "mower" : "cortacÈsped",
    "bottle screw" : "sacacarchos",
    "tin opener" : "abrelatas",
    "plumber's helper" : "ayudante de fontanero",
    "plough" : "arado",
    "chainsaw" : "motosierra",
    "Struthio camelus" : "Struthio camelus",
    "Fringilla montifringilla" : "fringilla montifringilla",
    "Carduelis carduelis" : "Carduelis carduelis",
    "linnet" : "lino",
    "Carpodacus mexicanus" : "carpodacus mexicanus",
    "snowbird" : "cocainÛmano",
    "indigo finch" : "pinzÛn Ìndigo",
    "indigo bird" : "p·jaro Ìndigo",
    "Passerina cyanea" : "cyanea del Passerina",
    "American robin" : "Petirrojo americano",
    "Turdus migratorius" : "migratorius del Turdus",
    "dipper" : "cazo",
    "American eagle" : "¡guila americana",
    "Haliaeetus leucocephalus" : "Haliaeetus",
    "great gray owl" : "b˙ho de gran gris",
    "Strix nebulosa" : "Strix nebulosa",
    "partridge" : "perdiz",
    "Bonasa umbellus" : "bono Umbllus",
    "prairie grouse" : "urogallo de las praderas",
    "prairie fowl" : "aves de pradera",
    "African gray" : "gris africano",
    "Psittacus erithacus" : "Psittacus erithacus",
    "Kakatoe galerita" : "galerita Kakatoe",
    "Cacatua galerita" : "galerita cacat˙a",
    "Mergus serrator" : "serrator mergus",
    "Cygnus atratus" : "Cygnus atratus",
    "Ciconia ciconia" : "ciconia ciconia",
    "Ciconia nigra" : "Ciconia nigra",
    "great white heron" : "gran garza blanca",
    "Egretta albus" : "albus Egretta",
    "Egretta caerulea" : "Egretta caerulea",
    "Aramus pictus" : "Aramus pictus",
    "marsh hen" : "gallina de pantano",
    "mud hen" : "gallina de barro",
    "water hen" : "gallina de agua",
    "Fulica americana" : "Fulica americana",
    "Arenaria interpres" : "Arenaria interpres",
    "dunlin" : "dunlin",
    "Erolia alpina" : "Erolia Alpine",
    "Tringa totanus" : "Tringa totanus",
    "oyster catcher" : "ostrero",
    "Porphyrio porphyrio" : "Guthrie",
    "Aptenodytes patagonica" : "patagonica del Aptenodytes",
    "mollymawk" : "mollymawk",
    "white shark" : "tiburÛn blanco",
    "man-eater" : "tigre cebado",
    "man-eating shark" : "devorador de hombres de tiburÛn",
    "Carcharodon carcharias" : "Carcharodon carcharias",
    "Galeocerdo cuvieri" : "galeocerdo cuvieri",
    "hammerhead shark" : "Tiburon martillo",
    "crampfish" : "crampfish",
    "numbfish" : "numbfish",
    "torpedo" : "torpedo",
    "snoek" : "lucio",
    "cohoe" : "coho",
    "coho salmon" : "salmÛn coho",
    "blue jack" : "jack azul",
    "silver salmon" : "salmones de plata",
    "Oncorhynchus kisutch" : "Oncorhynchus kisutch",
    "Tinca tinca" : "tinca tinca",
    "Carassius auratus" : "auratus",
    "Holocanthus tricolor" : "holocanthus tricolor",
    "pufferfish" : "pez globo",
    "blowfish" : "pez globo",
    "globefish" : "globefish",
    "garfish" : "aguja",
    "garpike" : "Garpike",
    "billfish" : "peces de pico",
    "Lepisosteus osseus" : "Ûseo Lepisosteus",
    "loggerhead turtle" : "tortuga boba",
    "Caretta caretta" : "Caretta caretta",
    "leatherback" : "la˙d",
    "leathery turtle" : "tortuga correosa",
    "Dermochelys coriacea" : "Dermochelys coriacea",
    "box tortoise" : "cuadro de tortuga",
    "iguana" : "iguana",
    "Iguana iguana" : " Iguana iguana",
    "anole" : "lagartijo",
    "Anolis carolinensis" : "Anolis carolinensis",
    "whiptail lizard" : "lagartija cola de l·tigo",
    "Chlamydosaurus kingi" : "zapatos Chlamydosaurus",
    "Heloderma suspectum" : "Heloderma suspectum",
    "Lacerta viridis" : "Lacerta viridis",
    "Chamaeleo chamaeleon" : "chamaeleon chamaeleo",
    "Komodo lizard" : "lagarto de Komodo",
    "dragon lizard" : "lagarto dragÛn",
    "giant lizard" : "lagarto gigante",
    "Varanus komodoensis" : "komodoensis varanus",
    "Nile crocodile" : "cocodrilo del Nilo",
    "Crocodylus niloticus" : "Crocodylus niloticus",
    "Alligator mississipiensis" : "mississipiensis cocodrilo",
    "worm snake" : "serpiente gusano",
    "Carphophis amoenus" : "Carphophis amoenus",
    "ring-necked snake" : "serpiente de collar",
    "ring snake" : "serpiente anillo",
    "puff adder" : "llamado de vibora",
    "kingsnake" : "Rey Serpiente",
    "grass snake" : "serpiente de hierba",
    "Hypsiglena torquata" : "torquata Hypsiglena",
    "Constrictor constrictor" : "constrictor constrictor",
    "rock snake" : "serpiente roca",
    "Python sebae" : "sebae Python",
    "Naja naja" : "Naja naja",
    "cerastes" : "cerastes",
    "sand viper" : "vÌbora de arena",
    "horned asp" : "asp cuernos",
    "Cerastes cornutus" : "cornutus cerastes",
    "diamondback rattlesnake" : "serpiente de cascabel",
    "Crotalus adamanteus" : "Crotalus adamanteus",
    "horned rattlesnake" : "serpiente de cascabel de cuernos",
    "Crotalus cerastes" : "Crotalus cerastes",
    "Salamandra salamandra" : " Salamandra salamandra",
    "Triturus vulgaris" : "Triturus vulgaris",
    "Ambystoma maculatum" : "Ambystoma maculatum",
    "mud puppy" : "cachorro de barro",
    "Ambystoma mexicanum" : "Ambystoma mexicanum",
    "Rana catesbeiana" : "Rana catesbeiana",
    "tree-frog" : "rana de ·rbol",
    "bell toad" : "campana de sapo",
    "ribbed toad" : "sapo acanalado",
    "tailed toad" : "sapo cola",
    "Ascaphus trui" : "suÈter ascaphus",
    "blow dryer" : "secador de cabello",
    "blow drier" : "el secador del soplo",
    "hair dryer" : "secador de pelo",
    "hair drier" : "Secadora de pelo",
    "speaker" : "altavoz",
    "speaker unit" : "unidad de altavoz",
    "loudspeaker system" : "sistema de altavoces",
    "speaker system" : "sistema de altavoces",
    "mike" : "micro",
    "CRT screen" : "la pantalla CRT",
    "computer mouse" : "ratÛn de computadora",
    "blower" : "soplador",
    "ruler" : "regla",
    "hodometer" : "hodÛmetro",
    "mileometer" : "cuentakilÛmetros",
    "milometer" : "cuentakilÛmetros",
    "weighing machine" : "bascula",
    "stop watch" : "cronÛmetro",
    "field glasses" : "gemelos",
    "opera glasses" : "Gafas de Ûpera",
    "dark glasses" : "lentes oscuros",
    "shades" : "sombras",
    "jeweler's loupe" : "una lupa de joyero",
    "radio reflector" : "reflector de radio",
    "assault gun" : "arma de asalto",
    "missile" : "misil",
    "keypad" : "teclado",
    "light" : "ligero",
    "igniter" : "encendedor",
    "ignitor" : "encendedor",
    "cash dispenser" : "cajero autom·tico",
    "automated teller machine" : "cajero autom·tico",
    "automatic teller machine" : "cajero autom·tico",
    "automated teller" : "cajero autom·tico",
    "automatic teller" : "cajero autom·tico",
    "ATM" : "Cajero autom·tico",
    "slipstick" : "Slipstick",
    "hand-held microcomputer" : "microordenador port·til",
    "notebook computer" : "Ordenador portatil",
    "website" : "sitio web",
    "internet site" : "sitio de Internet",
    "site" : "sitio",
    "reaper" : "segador",
    "thrasher" : "Thrasher",
    "threshing machine" : "trilladora",
    "one-armed bandit" : "con un solo brazo bandido",
    "electric switch" : "interruptor elÈctrico",
    "electrical switch" : "interruptor elÈctrico",
    "claw" : "garra",
    "paddle wheel" : "Rueda de paletas",
    "gasoline pump" : "bomba de gasolina",
    "petrol pump" : "bomba de gasolina",
    "island dispenser" : "dispensador de la isla",
    "carrousel" : "carrusel",
    "merry-go-round" : "tiovivo",
    "roundabout" : "rotonda",
    "whirligig" : "molinete",
    "hockey puck" : "disco de hockey",
    "hard disk" : "disco duro",
    "fixed disk" : "disco fijo",
    "plectrum" : "v·lvula",
    "plectron" : "PLECTRONIA",
    "solar collector" : "BaterÌa solar",
    "solar furnace" : "horno solar",
    "remote" : "remoto",
    "disc brake" : "freno de disco",
    "seatbelt" : "cinturÛn de seguridad",
    "taper" : "afilar",
    "wax light" : "la luz de cera",
    "spot" : "lugar",
    "spider's web" : "telaraÒa",
    "daddy longlegs" : "pap· piernas largas",
    "Phalangium opilio" : "opilio phalangium",
    "Argiope aurantia" : "Argiope aurantia",
    "Araneus cavaticus" : "cavaticus Araneus",
    "Aranea diademata" : "Las coronas de araÒa",
    "Latrodectus mactans" : "Latrodectus mactans",
    "hunting spider" : "araÒa de caza",
    "Cancer magister" : "Magister c·ncer",
    "Cancer irroratus" : "irroratus el c·ncer",
    "Alaska crab" : "cangrejo de Alaska",
    "Alaskan king crab" : "cangrejo real de Alaska",
    "Alaska king crab" : "Alaska cangrejo real",
    "Paralithodes camtschatica" : "camtschatica Paralithodes",
    "Northern lobster" : "langosta del Norte",
    "Maine lobster" : "langosta de Maine",
    "Homarus americanus" : "Homarus americanus",
    "langouste" : "cangrejo de rÌo",
    "rock lobster" : "Langosta de roca",
    "crayfish" : "cangrejo de rÌo",
    "sea crawfish" : "cangrejos de mar",
    "crawfish" : "cangrejo de rÌo",
    "crawdad" : "crawdad",
    "crawdaddy" : "crawdaddy",
    "ladybeetle" : "ladybeetle",
    "lady beetle" : "escarabajo de seÒora",
    "ladybird" : "mariquita",
    "ladybird beetle" : "mariquita",
    "carabid beetle" : "escarabajo carabid",
    "longicorn" : "longicorn",
    "longicorn beetle" : "escarabajo longicorn",
    "chrysomelid" : "chrysomelid",
    "hopper" : "tolva",
    "walkingstick" : "bastÛn",
    "stick insect" : "insecto palo",
    "roach" : "cucaracha",
    "mantid" : "mantis",
    "cicala" : "cigarra",
    "lacewing fly" : "mosca crisopa",
    "darning needle" : "aguja de zurcir",
    "devil's darning needle" : "aguja de zurcir del diablo",
    "sewing needle" : "aguja de coser",
    "snake feeder" : "alimentador de serpiente",
    "snake doctor" : "mÈdico de la serpiente",
    "mosquito hawk" : "halcÛn de mosquito",
    "skeeter hawk" : "halcÛn skeeter",
    "ringlet butterfly" : "mariposa rizo",
    "monarch butterfly" : "mariposa monarca",
    "milkweed butterfly" : "mariposa algodoncillo",
    "Danaus plexippus" : "Danaus plexippus",
    "sulfur butterfly" : "mariposa de azufre",
    "lycaenid butterfly" : "mariposa lycaenid",
    "anemone" : "anÈmona",
    "platyhelminth" : "platelminto",
    "nematode worm" : "gusano nematodo",
    "roundworm" : "lombriz",
    "nudibranch" : "nudibranquio",
    "coat-of-mail shell" : "escudo de la c·scara electrÛnico",
    "sea cradle" : "cuna mar",
    "polyplacophore" : "polyplacophore",
    "holothurian" : "holoturias",
    "smoothing iron" : "plancha",
    "microwave oven" : "horno microondas",
    "vacuum cleaner" : "aspiradora",
    "dish washer" : "lavavajillas",
    "dishwashing machine" : "maquina lavaplatos",
    "icebox" : "nevera",
    "automatic washer" : "lavadora autom·tica",
    "washing machine" : "lavadora",
    "frypan" : "sartÈn",
    "skillet" : "sartÈn",
    "cauldron" : "caldera",
    "terrace" : "terraza",
    "nursery" : "vivero",
    "glasshouse" : "invernadero",
    "bee house" : "casa de abeja",
    "church building" : "edificio de la iglesia",
    "tope" : " tope",
    "eating house" : "casa de comidas",
    "eating place" : "Lugar de comer",
    "eatery" : "restaurante",
    "movie theater" : "cine",
    "movie theatre" : "cine",
    "movie house" : "cine",
    "picture palace" : "iMAGEN del palacio",
    "home theatre" : "teatro en casa",
    "sawmill" : "aserradero",
    "spiral" : "espiral",
    "volute" : "volutas",
    "whorl" : "espira",
    "helix" : "hÈlice",
    "prison house" : "c·rcel",
    "grocery" : "tienda de comestibles",
    "food market" : "comida de mercado",
    "market" : "mercado",
    "bakeshop" : "pastelerÌa",
    "bakehouse" : "panaderÌa",
    "bookstore" : "librerÌa",
    "bookstall" : "puesto de libros",
    "meat market" : "mercado de carne",
    "confectionary" : "confiterÌa",
    "candy store" : "tienda de golosinas",
    "shoe-shop" : "tienda de zapatos",
    "shoe store" : "zapaterÌa",
    "tobacconist shop" : "estanco",
    "tobacconist" : "estanquero",
    "dockage" : "estaciÛn del barco",
    "docking facility" : "las instalaciones de atraque",
    "memorial tablet" : "l·pida",
    "plaque" : "placa",
    "megalithic structure" : "estructura megalÌtica",
    "banister" : "barandilla",
    "balustrade" : "barandillas",
    "balusters" : "barandilla",
    "handrail" : "pretil",
    "groin" : "ingle",
    "groyne" : "rompeolas",
    "mole" : "Topo",
    "bulwark" : "baluarte",
    "seawall" : "rompeolas",
    "jetty" : "embarcadero",
    "dike" : "nuestro",
    "dyke" : "dique",
    "paling" : "m·s",
    "snake fence" : "valla de serpiente",
    "snake-rail fence" : "valla de serpiente-rail",
    "Virginia fence" : "valla de Virginia",
    "radiator grille" : "parrilla del radiador",
    "plinth" : "zÛcalo",
    "footstall" : "footstall",
    "lighthouse" : "faro",
    "beacon light" : "Faro de luz",
    "pharos" : "Pharos",
    "courgette" : "calabacÌn",
    "cuke" : "tener",
    "globe artichoke" : "alcachofa",
    "blue jean" : "pantalones vaqueros",
    "denim" : "mezclilla",
    "hankie" : "paÒuelo",
    "hanky" : "paÒuelo",
    "hankey" : "Hankey",
    "trash can" : "bote de basura",
    "garbage can" : "basura",
    "wastebin" : "cubo de la basura",
    "ash bin" : "ash bin",
    "ash-bin" : "cubo de la basura",
    "ashbin" : "Ashby",
    "dustbin" : "basura",
    "trash barrel" : "cubo de basura",
    "trash bin" : "contenedor de basura",
    "pyjama" : "pijama",
    "pj's" : "pj",
    "jammies" : "pijama",
    "vat" : "tina",
    "beam" : "haz",
    "beigel" : "Beigel",
    "prayer mat" : "alfombra para rezar",
    "hotpot" : "estofado",
    "dust cover" : "guardapolvo",
    "dust jacket" : "sobrecubierta",
    "dust wrapper" : "envoltorio de polvo",
    "swimming cap" : "gorra de nataciÛn",
    "teddy bear" : "oso de peluche",
    "soda bottle" : "botella de refresco",
    "crossword" : "crucigrama",
    "suit of clothes" : "juego de la ropa",
    "boa" : "bueno",
    "buckler" : "escudo",
    "crinoline" : "miriÒaque",
    "poke bonnet" : "sombrero poke",
    "meatloaf" : "pastel de carne",
    "sunblock" : "bloqueador solar",
    "sun blocker" : "bloqueador de sol",
    "hen of the woods" : "gallina de los bosques",
    "Polyporus frondosus" : "frondosus polyporus",
    "Grifola frondosa" : "Grifola frondosa",
    "lamp shade" : "pantalla de l·mpara",
    "woolen" : "de lana",
    "woollen" : "de lana",
    "bow-tie" : "corbata de moÒo",
    "bowtie" : "corbata de moÒo",
    "postbag" : "correspondencia",
    "pail" : "cubo",
    "dishcloth" : "paÒo de cocina",
    "boat paddle" : "bote de remos",
    "swob" : "escobillÛn",
    "mop" : "fregona",
    "offshore rig" : "plataforma submarina",
    "ring-binder" : "carpeta de anillas",
    "flowerpot" : "maceta",
    "pencil case" : "estuche",
    "pay-station" : "pay-estaciÛn",
    "punch bag" : "bolsa de golpear",
    "punching ball" : "bolsa de boxeo",
    "punchball" : "bola de golpe",
    "back pack" : "mochila",
    "knapsack" : "mochila",
    "packsack" : "packsack",
    "rucksack" : "mochila",
    "haversack" : "mochila",
    "bridegroom" : "novio",
    "busby" : "gorro alto de piel negra",
    "shako" : "chacÛ",
    "Polaroid Land camera" : "la c·mara Polaroid Land",
    "racquet" : "raqueta",
    "traffic signal" : "seÒal de tr·fico",
    "stoplight" : "luz de freno",
    "quill pen" : "pluma pluma",
    "wireless" : "inal·mbrico",
    "lip rouge" : "rojo de labios",
    "scope" : "alcance",
    "cathode-ray oscilloscope" : "osciloscopio de rayos catÛdicos",
    "CRO" : "CRO",
    "bra" : "bueno",
    "bandeau" : "cinta para el pelo",
    "mini" : "mini",
    "ten-gallon hat" : "sombrero de diez galones",
    "trolley coach" : "entrenador del carro",
    "trackless trolley" : "sin caminos carro",
    "essence" : "esencia",
    "bathing tub" : "tina de baÒo",
    "bath" : "baÒera",
    "tub" : "tina",
    "hot dog" : "Pancho",
    "red hot" : "al rojo vivo",
    "bullet" : "bala",
    "toilet paper" : "papel higienico",
    "bathroom tissue" : "papel de baÒo",
    "tool kit" : "juego de herramientas",
    "carrion fungus" : "hongo carroÒa",
    "academic robe" : "bata acadÈmico",
    "judge's robe" : "la t˙nica de juez",
    "ring mail" : "anillo electrÛnico",
    "mail" : "correo",
    "chain armor" : "cota de malla",
    "chain armour" : "cota de malla",
    "ring armor" : "armadura del anillo",
    "ring armour" : "armadura del anillo",
    "theatre curtain" : "cortina de teatro",
    "cask" : "barril",
    "handbasin" : "lava manos",
    "washbowl" : "lavabo",
    "lavabo" : "lavabo",
    "wash-hand basin" : "lavamanos",
    "ballpoint pen" : "bolÌgrafo",
    "ballpen" : "bolÌgrafo",
    "Biro" : "oficina",
    "cellular phone" : "telÈfono celular",
    "cellphone" : "TelÈfono mÛvil",
    "cell" : "celda",
    "mobile phone" : "telÈfono mÛvil",
    "letter box" : "buzÛn",
    "laboratory coat" : "bata de laboratorio",
    "fireguard" : "bombero",
    "labyrinth" : "laberinto",
    "high bar" : "barra alta",
    "billfold" : "cartera",
    "notecase" : "cartera",
    "pocketbook" : "cartera",
    "penny bank" : "penny bank",
    "bell cot" : "campana cuna",
    "bolo" : "era",
    "bola tie" : "fue el",
    "bola" : "era",
    "chute" : "caÌda",
    "television system" : "sistema de televisiÛn",
    "bathing trunks" : "baÒador",
    "pizza pie" : "pizza",
    "aegis" : "Ègida",
    "egis" : "EGIS",
    "salt shaker" : "salero",
    "chocolate syrup" : "sirope de chocolate",
    "baseball player" : "jugador de baseball",
    "dial phone" : "TelÈfono directo",
    "T-shirt" : "camiseta",
    "tee shirt" : "camiseta",
    "nappy" : "paÒal",
    "napkin" : "servilleta",
    "lolly" : "polo",
    "lollipop" : "chupete",
    "popsicle" : "popsicle",
    "respirator" : "respirador",
    "gas helmet" : "casco de gas",
    "welcome mat" : "Alfombra de bienvenida",
    "icecream" : "helado",
    "comforter" : "edredÛn",
    "comfort" : "comodidad",
    "puff" : "soplo",
    "tank suit" : "traje de tanque",
    "geta" : "lata",
    "patten" : "zueco",
    "sabot" : "pezuÒa",
    "ewer" : "aguamanil",
    "two-piece" : "dos piezas",
    "lens cover" : "cubierta de la lente",
    "thatch" : "paja",
    "thatched roof" : "techo de paja",
    "bars" : "barras",
    "flagstaff" : "asta de bandera",
    "rubber" : "caucho",
    "pencil eraser" : "borrador de l·piz"
]
